
jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      #Python38:
        #python.version: '3.8' #vtk doesn't work for python 3.8 yet..
  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to path
  - script: |
        conda create -y -n mwi python=$(python.version)
        call activate mwi
        conda install -y --file requirements.txt
        pip install terminaltables tqdm
        pip install -e .
    displayName: Setup conda
  - script: |
        call activate mwi
        git clone https://github.com/gprMax/gprMax.git
        cd gprMax
        python setup.py build
        python setup.py install
    displayName: Setup gprMax
  - script: |
        call activate mwi
        python -m nose tests
    displayName: Run tests
